### ISSUE TITLE
Question about makefile syntax

### ISSUE THREAD

**Issue by cskwrd** [alexellis/firecracker-init-lab#2]
What do the characters after the command mean on this line: https://github.com/alexellis/firecracker-init-lab/blob/master/Makefile#L34

I've never come across them in this sequence before.

**Comment by alexellis** [comment]
Hi ` X || :` means do X and pass with exit code 0 if it gives a non-zero exit code

Have you tried the lab already?

**Comment by cskwrd** [comment]
Thank you. I haven't yet I was reading the make file to understand it.
